### ISSUE TITLE
Build for Scala 2.13.0

### ISSUE THREAD

**Issue by FabioPinheiro** [japgolly/univeq#22]
We need to support Scala 2.13 so we can build scalacss for 2.13 also. As it depends on this https://github.com/japgolly/scalacss/issues/153

**Comment by FabioPinheiro** [comment]
I seems to be building for scala 2.13 but is not publish.
https://mvnrepository.com/artifact/com.github.japgolly.univeq/univeq
@japgolly Is there a reason for it?

**Comment by FabioPinheiro** [comment]
Can you merge this PR https://github.com/japgolly/univeq/pull/23 before publish?

**Comment by japgolly** [comment]
Oh wow you're right, I thought I already published a release already with Scala 2.13 support. Too many things in my mind this yeah, I guess I just forgot. :) Ok I'll merge #23 and publish this today.

**Comment by japgolly** [comment]
v1.1.0-RC1 is on its way to Maven Central.
